# Use the Ubuntu 25.10 development codename, Questing Quokka
FROM ubuntu:questing

#! VAAPI
#& hls-restream
#^ General
WORKDIR /usr/src

#^ Install applications, drivers, and runtime libraries
RUN set -eux; apt update; \
    DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
    #& hls-restream dependencies
    nginx \
    supervisor \
    #^ FFmpeg
    ffmpeg \
    #! Video Acceleration (VA) API for Linux
    vainfo \
    #!  Intel-specific drivers (Alder Lake / 12th Gen+)
    intel-media-va-driver-non-free \
    libvpl2 \
    #! AMD/Generic drivers (Ensures the image isn't "locked" to Intel)
    # mesa-va-drivers \
    #! Essential for VA-API to talk to the DRM (Direct Rendering Manager)
    libva-drm2 \
    #^ Standard SSL certs (required if ffmpeg needs to pull via https)
    ca-certificates \
    #^ Cleanup temporary files and package lists
    && rm -rf /var/lib/apt/lists/*


#& Configure nginx and supervisor
ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN mkdir -p /var/log/supervisor; \
    mkdir -p /var/www/html; \
    groupadd --gid $USER_GID $USERNAME; \
    useradd --uid $USER_UID --gid $USERNAME --shell /bin/bash --create-home $USERNAME; \
    chown $USERNAME /var/www/html;

COPY supervisord.conf entrypoint.sh ./
COPY profiles profiles
COPY player.html /var/www/html/index.html
COPY nginx.conf /etc/nginx/sites-enabled/default

#! Environmental tweaks for hardware stability
#! We don't hardcode vaapi driver here so the system can auto-detect (Intel (iHD) vs AMD (radeonsi) vs Generic.)
ENV NVC_PROMPT_RELEASE=1

ENV USER=$USERNAME

CMD ["./entrypoint.sh"]